-- Automatically generated, do not edit.
\set ON_ERROR_STOP 1

SET search_path = 'sitemaps';

TRUNCATE TABLE artist_lastmod RESTART IDENTITY CASCADE;
TRUNCATE TABLE control RESTART IDENTITY CASCADE;
TRUNCATE TABLE label_lastmod RESTART IDENTITY CASCADE;
TRUNCATE TABLE place_lastmod RESTART IDENTITY CASCADE;
TRUNCATE TABLE recording_lastmod RESTART IDENTITY CASCADE;
TRUNCATE TABLE release_group_lastmod RESTART IDENTITY CASCADE;
TRUNCATE TABLE release_lastmod RESTART IDENTITY CASCADE;
TRUNCATE TABLE tmp_checked_entities RESTART IDENTITY CASCADE;
TRUNCATE TABLE work_lastmod RESTART IDENTITY CASCADE;
