#!/usr/bin/env perl
use strict;
use warnings;

use FindBin '$Bin';
use lib "$Bin/../../lib";

use DBDefs;
use DBI;
use Getopt::Long;
use MusicBrainz::Server::Context;
use Pod::Usage;

my $c = MusicBrainz::Server::Context->create_script_context;
my $locks = $c->sql->select_single_value("SELECT count(*) FROM pg_locks");

my $message = "postgres reports $locks locks";

my ($exitcode, $exitmessage) = (
      $locks > 1000 ? (2, "CRITICAL: $message")
    : $locks > 500  ? (1, "WARNING: $message")
    :                 (0, "OK: $message")
);

print $exitmessage, "\n";
exit $exitcode;

1;
