rules:
  no-await-in-loop: error
  eqeqeq: [warn, smart]
  wrap-iife: warn
  camelcase: [warn, {properties: never,
                     allow: [
                       "l_attributes",
                       "ln_attributes",
                       "lp_attributes",
                       "l_countries",
                       "ln_countries",
                       "lp_countries",
                       "l_instrument_descriptions",
                       "ln_instrument_descriptions",
                       "lp_instrument_descriptions",
                       "l_instruments",
                       "ln_instruments",
                       "lp_instruments",
                       "l_languages",
                       "ln_languages",
                       "lp_languages",
                       "l_relationships",
                       "ln_relationships",
                       "lp_relationships",
                       "l_scripts",
                       "ln_scripts",
                       "lp_scripts",
                       "l_statistics",
                       "ln_statistics",
                       "lp_statistics",
                       "N_l",
                       "N_ln",
                       "N_lp",
                     ]}]
  consistent-this: [warn, self]
  operator-assignment: [warn, always]
  operator-linebreak: [warn, after, {overrides: {?: before, :: before}}]
  quotes: [warn, single, {avoidEscape: true,
                          allowTemplateLiterals: true}]
  sort-keys: [warn, asc, {caseSensitive: false, natural: true}]
  space-before-function-paren: [warn, {anonymous: always,
                                       named: never,
                                       asyncArrow: always}]
  no-var: warn
  prefer-const: warn
  import/first: warn
  import/no-commonjs: error
  import/order: [warn, {newlines-between: always}]
  react/no-access-state-in-setstate: error
  react/no-multi-comp: [warn, {ignoreStateless: true}]
  react/no-render-return-value: warn
  react/prefer-stateless-function: warn
  react/sort-comp: [warn, {order: [type-annotations,
                                   static-methods,
                                   lifecycle,
                                   everything-else,
                                   render]}]
  react/jsx-no-bind: [warn, {ignoreDOMComponents: true}]
  flowtype/no-types-missing-file-annotation: error
  flowtype/no-weak-types: warn
  react-hooks/exhaustive-deps: warn
