rules:
  no-await-in-loop: error
  eqeqeq: [warn, smart]
  wrap-iife: warn
  camelcase: [warn, {properties: never,
                     allow: [
                       "l_admin",
                       "ln_admin",
                       "l_attributes",
                       "ln_attributes",
                       "lp_attributes",
                       "l_countries",
                       "ln_countries",
                       "lp_countries",
                       "l_history",
                       "l_instrument_descriptions",
                       "ln_instrument_descriptions",
                       "lp_instrument_descriptions",
                       "l_instruments",
                       "ln_instruments",
                       "lp_instruments",
                       "l_languages",
                       "ln_languages",
                       "lp_languages",
                       "l_mb_server",
                       "ln_mb_server",
                       "lp_mb_server",
                       "l_relationships",
                       "ln_relationships",
                       "lp_relationships",
                       "l_reports",
                       "l_scripts",
                       "ln_scripts",
                       "lp_scripts",
                       "l_statistics",
                       "ln_statistics",
                       "lp_statistics",
                       "N_l",
                       "N_ln",
                       "N_lp",
                       "N_l_mb_server",
                       "N_ln_mb_server",
                       "N_lp_mb_server",
                       "N_l_reports",
                       "N_l_statistics",
                       "N_lp_statistics",
                       "__webpack_public_path__",
                     ]}]
  consistent-this: [warn, self]
  sort-keys: [warn, asc, {caseSensitive: false, natural: true}]
  no-var: warn
  prefer-const: warn
  react/no-access-state-in-setstate: error
  react/no-multi-comp: [warn, {ignoreStateless: true}]
  react/no-render-return-value: warn
  react/jsx-no-bind: [warn, {ignoreDOMComponents: true}]
