rules:
  no-await-in-loop: error
  eqeqeq: [warn, smart]
  wrap-iife: warn
  camelcase: [warn, {properties: never,
                     allow: [
                       "l_attributes",
                       "ln_attributes",
                       "lp_attributes",
                       "l_countries",
                       "ln_countries",
                       "lp_countries",
                       "l_instrument_descriptions",
                       "ln_instrument_descriptions",
                       "lp_instrument_descriptions",
                       "l_instruments",
                       "ln_instruments",
                       "lp_instruments",
                       "l_languages",
                       "ln_languages",
                       "lp_languages",
                       "l_relationships",
                       "ln_relationships",
                       "lp_relationships",
                       "l_scripts",
                       "ln_scripts",
                       "lp_scripts",
                       "l_statistics",
                       "ln_statistics",
                       "lp_statistics",
                       "N_l",
                       "N_ln",
                       "N_lp",
                     ]}]
  consistent-this: [warn, self]
  sort-keys: [warn, asc, {caseSensitive: false, natural: true}]
  no-var: warn
  prefer-const: warn
  react/no-access-state-in-setstate: error
  react/no-multi-comp: [warn, {ignoreStateless: true}]
  react/no-render-return-value: warn
  react/jsx-no-bind: [warn, {ignoreDOMComponents: true}]
  flowtype/no-types-missing-file-annotation: error
  flowtype/no-weak-types: warn
