#!/bin/sh

set -o errexit
cd `dirname $0`

echo `date` : Upgrading to RELEASE_20041009-BRANCH

echo `date` : Producing replication packet
./admin/RunExport

echo `date` : Creating initial CDTOC data
./admin/sql/updates/20040730-1.pl
# Keep the data safe, so mirrors can download it
[ -w /var/ftp/pub/musicbrainz/data ] && cp -v /tmp/20040730-*.dat /var/ftp/pub/musicbrainz/data/

echo `date` : Upgrading database
./admin/psql READWRITE < ./admin/sql/updates/20040730-2.sql
./admin/psql READWRITE < ./admin/sql/updates/20040916-1.sql

echo `date` : Going to schema sequence 3
echo "UPDATE replication_control SET current_schema_sequence = 3;" | ./admin/psql READWRITE
perl -i -pwe 's/\b\d+\b/3/ if m/^sub DB_SCHEMA_SEQUENCE /' ./cgi-bin/DBDefs.pm

echo `date` : Done

# eof
