requires 'perl' => '5.42.0';

# Dependencies needed only to execute ./admin/InitDb.pl.

requires 'aliased'              => '0.34';
requires 'DBD::Pg'              => '3.20.0';
requires 'DBIx::Connector'      => '0.60';
requires 'JSON'                 => '4.11';
requires 'JSON::XS'             => '4.04';
requires 'Moose'                => '2.4000';
requires 'String::ShellQuote'   => '1.04';
requires 'Throwable'            => '1.001';
requires 'DateTime::Duration'   => '1.66';
requires 'File::Slurp';
requires 'List::AllUtils'       => '0.03';
requires 'Readonly'             => '1.04';
requires 'File::Spec'           => '3.75';
