# Only put steps here that are common to both the js-perl-and-pgtap and
# selenium jobs.

name: setup-tests-container
description: 'Sets up the musicbrainz-tests container for tests execution'
runs:
  using: 'composite'
  steps:
    - run: |
        ln -s "$GITHUB_WORKSPACE" "$MBS_ROOT"
        chown -R musicbrainz:musicbrainz .
        corepack enable
      shell: bash

    - id: cache-restore-node-modules
      uses: actions/cache/restore@v4
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('yarn.lock') }}

    - if: steps.cache-restore-node-modules.outputs.cache-hit == 'true'
      run: |
        chown -R musicbrainz:musicbrainz node_modules
      shell: bash

    - if: steps.cache-restore-node-modules.outputs.cache-hit != 'true'
      run: |
        sudo -E -H -u musicbrainz yarn
      shell: bash

    - if: steps.cache-restore-node-modules.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: node_modules
        key: ${{ steps.cache-restore-node-modules.outputs.cache-primary-key }}

    - run: |
        /sbin/my_init &
        sleep 5
        sudo -E -H -u musicbrainz cp docker/musicbrainz-tests/DBDefs.pm lib/
        rm -fv /etc/service/{postgresql,redis}/down
        sv -w 30 start postgresql redis
        sudo -E -H -u musicbrainz carton exec -- ./script/create_test_db.sh
        sudo -E -H -u musicbrainz make -C po all_quiet deploy
        sudo -E -H -u musicbrainz mkdir -p junit_output
      shell: bash
