// flow-typed signature: d64dc5b25c1eb04c0354551df203b4e7
// flow-typed version: <<STUB>>/blobs_v^2.3.0-beta.2/flow_v0.273.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blobs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blobs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blobs/index.module' {
  declare module.exports: any;
}

declare module 'blobs/v1' {
  declare module.exports: any;
}

declare module 'blobs/v1/index.module' {
  declare module.exports: any;
}

declare module 'blobs/v2/animate' {
  declare module.exports: any;
}

declare module 'blobs/v2/animate/index.module' {
  declare module.exports: any;
}

declare module 'blobs/v2' {
  declare module.exports: any;
}

declare module 'blobs/v2/index.module' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blobs/index' {
  declare module.exports: $Exports<'blobs'>;
}
declare module 'blobs/index.js' {
  declare module.exports: $Exports<'blobs'>;
}
declare module 'blobs/index.module.js' {
  declare module.exports: $Exports<'blobs/index.module'>;
}
declare module 'blobs/v1/index' {
  declare module.exports: $Exports<'blobs/v1'>;
}
declare module 'blobs/v1/index.js' {
  declare module.exports: $Exports<'blobs/v1'>;
}
declare module 'blobs/v1/index.module.js' {
  declare module.exports: $Exports<'blobs/v1/index.module'>;
}
declare module 'blobs/v2/animate/index' {
  declare module.exports: $Exports<'blobs/v2/animate'>;
}
declare module 'blobs/v2/animate/index.js' {
  declare module.exports: $Exports<'blobs/v2/animate'>;
}
declare module 'blobs/v2/animate/index.module.js' {
  declare module.exports: $Exports<'blobs/v2/animate/index.module'>;
}
declare module 'blobs/v2/index' {
  declare module.exports: $Exports<'blobs/v2'>;
}
declare module 'blobs/v2/index.js' {
  declare module.exports: $Exports<'blobs/v2'>;
}
declare module 'blobs/v2/index.module.js' {
  declare module.exports: $Exports<'blobs/v2/index.module'>;
}
