// flow-typed signature: f080e5e8320738d6f238e66beb9c0959
// flow-typed version: <<STUB>>/swiper_v^11.2.10/flow_v0.273.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swiper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swiper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swiper/swiper-bundle' {
  declare module.exports: any;
}

declare module 'swiper/swiper-bundle.min' {
  declare module.exports: any;
}

declare module 'swiper/swiper-element-bundle' {
  declare module.exports: any;
}

declare module 'swiper/swiper-element-bundle.min' {
  declare module.exports: any;
}

declare module 'swiper/swiper-element' {
  declare module.exports: any;
}

declare module 'swiper/swiper-element.min' {
  declare module.exports: any;
}

declare module 'swiper/swiper' {
  declare module.exports: any;
}

declare module 'swiper/swiper.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swiper/swiper-bundle.js' {
  declare module.exports: $Exports<'swiper/swiper-bundle'>;
}
declare module 'swiper/swiper-bundle.min.js' {
  declare module.exports: $Exports<'swiper/swiper-bundle.min'>;
}
declare module 'swiper/swiper-element-bundle.js' {
  declare module.exports: $Exports<'swiper/swiper-element-bundle'>;
}
declare module 'swiper/swiper-element-bundle.min.js' {
  declare module.exports: $Exports<'swiper/swiper-element-bundle.min'>;
}
declare module 'swiper/swiper-element.js' {
  declare module.exports: $Exports<'swiper/swiper-element'>;
}
declare module 'swiper/swiper-element.min.js' {
  declare module.exports: $Exports<'swiper/swiper-element.min'>;
}
declare module 'swiper/swiper.js' {
  declare module.exports: $Exports<'swiper/swiper'>;
}
declare module 'swiper/swiper.min.js' {
  declare module.exports: $Exports<'swiper/swiper.min'>;
}
