drop trigger a_ins_album on album; 
drop trigger a_del_album on album; 
drop trigger a_ins_albumjoin on albumjoin; 
drop trigger a_del_albumjoin on albumjoin; 
drop trigger a_ins_discid on discid; 
drop trigger a_del_discid on discid; 
drop trigger a_ins_trmjoin on trmjoin; 
drop trigger a_del_trmjoin on trmjoin; 
drop trigger b_upd_moderation on moderation; 
