begin;
drop index  albumwords_albumidindex;
drop index  albumwords_albumwordindex;
drop index  albumwords_wordidindex;
drop index  artistwords_artistidindex;
drop index  artistwords_artistwordindex;
drop index  artistwords_wordidindex;
drop index  trackwords_trackidindex;
drop index  trackwords_trackwordindex;
drop index  trackwords_wordidindex;
drop index  wordlist_wordindex;
delete from albumwords;
delete from artistwords;
delete from trackwords;
delete from wordlist;
commit;
vacuum analyze;
