drop function fill_album_meta();
drop function insert_album_meta();
drop function delete_album_meta();
drop function increment_track_count();
drop function decrement_track_count();
drop function increment_discid_count();
drop function decrement_discid_count();
drop function increment_trmid_count();
drop function decrement_trmid_count();
