\unset ON_ERROR_STOP

DROP INDEX edit_add_relationship_link_type;
DROP INDEX edit_edit_relationship_link_type_link;
DROP INDEX edit_edit_relationship_link_type_new;
DROP INDEX edit_edit_relationship_link_type_old;
