-- Automatically generated, do not edit.
\unset ON_ERROR_STOP

DROP TRIGGER a_ins_release_slave ON release;
DROP TRIGGER a_upd_release_slave ON release;
DROP TRIGGER a_del_release_slave ON release;
DROP TRIGGER a_ins_release_event_slave ON release_country;
DROP TRIGGER a_upd_release_event_slave ON release_country;
DROP TRIGGER a_del_release_event_slave ON release_country;
DROP TRIGGER a_ins_release_event_slave ON release_unknown_country;
DROP TRIGGER a_upd_release_event_slave ON release_unknown_country;
DROP TRIGGER a_del_release_event_slave ON release_unknown_country;
DROP TRIGGER a_ins_release_group_slave ON release_group;
DROP TRIGGER a_upd_release_group_slave ON release_group;
DROP TRIGGER a_del_release_group_slave ON release_group;
DROP TRIGGER a_upd_release_group_meta_slave ON release_group_meta;
DROP TRIGGER a_ins_release_group_secondary_type_join_slave ON release_group_secondary_type_join;
DROP TRIGGER a_del_release_group_secondary_type_join_slave ON release_group_secondary_type_join;
DROP TRIGGER a_ins_release_label_slave ON release_label;
DROP TRIGGER a_upd_release_label_slave ON release_label;
DROP TRIGGER a_del_release_label_slave ON release_label;
DROP TRIGGER a_ins_track_slave ON track;
DROP TRIGGER a_upd_track_slave ON track;
DROP TRIGGER a_del_track_slave ON track;
DROP TRIGGER apply_artist_release_group_pending_updates_slave ON release;
DROP TRIGGER apply_artist_release_pending_updates_slave ON release;
DROP TRIGGER apply_artist_release_pending_updates_slave ON release_country;
DROP TRIGGER apply_artist_release_pending_updates_slave ON release_first_release_date;
DROP TRIGGER apply_artist_release_group_pending_updates_slave ON release_group;
DROP TRIGGER apply_artist_release_group_pending_updates_slave ON release_group_meta;
DROP TRIGGER apply_artist_release_group_pending_updates_slave ON release_group_secondary_type_join;
DROP TRIGGER apply_artist_release_pending_updates_slave ON release_label;
DROP TRIGGER apply_artist_release_group_pending_updates_slave ON track;
DROP TRIGGER apply_artist_release_pending_updates_slave ON track;
