FROM phusion/baseimage:0.11

RUN useradd --create-home --shell /bin/bash musicbrainz

WORKDIR /home/musicbrainz

COPY docker/yarn_pubkey.txt .

RUN apt-get update && \
    apt-get install \
        --no-install-recommends \
        --no-install-suggests \
        -y \
        ca-certificates \
        curl \
        gnupg && \
    apt-key add yarn_pubkey.txt && \
    rm yarn_pubkey.txt && \
    apt-key adv --keyserver keyserver.ubuntu.com --refresh-keys 'Yarn' && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    curl -sLO https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    curl -sLO https://deb.nodesource.com/node_10.x/pool/main/n/nodejs/nodejs_10.17.0-1nodesource1_amd64.deb && \
    apt-get update && \
    apt-get install \
        --no-install-recommends \
        --no-install-suggests \
        -y \
        ./google-chrome-stable_current_amd64.deb \
        ./nodejs_10.17.0-1nodesource1_amd64.deb \
        build-essential \
        bzip2 \
        gcc \
        gettext \
        git \
        language-pack-de \
        language-pack-el \
        language-pack-es \
        language-pack-et \
        language-pack-fi \
        language-pack-fr \
        language-pack-it \
        language-pack-ja \
        language-pack-nl \
        language-pack-sq \
        libc6-dev \
        libdb-dev \
        libdb5.3 \
        libexpat1 \
        libexpat1-dev \
        libicu-dev \
        libicu60 \
        libperl-dev \
        libpq-dev \
        libpq5 \
        libssl-dev \
        libssl1.0.0 \
        libxml2 \
        libxml2-dev \
        locales \
        lsof \
        make \
        maven \
        openjdk-8-jdk \
        openjdk-8-jre \
        openssh-client \
        perl \
        pkg-config \
        postgresql \
        postgresql-10-pgtap \
        postgresql-contrib \
        postgresql-server-dev-10 \
        python2.7-dev \
        python2.7-minimal \
        rabbitmq-server \
        redis-server \
        runit \
        runit-systemd \
        sudo \
        unzip \
        virtualenv \
        yarn && \
    rm -rf /var/lib/apt/lists/* && \
    rm google-chrome-stable_current_amd64.deb && \
    rm nodejs_10.17.0-1nodesource1_amd64.deb && \
    update-java-alternatives -s java-1.8.0-openjdk-amd64 && \
    systemctl disable rabbitmq-server

ENV PG_AMQP_TAG v0.4.1

RUN git clone --branch $PG_AMQP_TAG --depth 1 https://github.com/omniti-labs/pg_amqp.git && \
    cd pg_amqp && \
    make && \
    make install && \
    cd /home/musicbrainz

ENV SOLR_VERSION 7.7.2
ENV SOLR_HOME /opt/solr/server/solr

RUN curl -sLO https://www.apache.org/dist/lucene/solr/$SOLR_VERSION/solr-$SOLR_VERSION.tgz && \
    tar xzf solr-$SOLR_VERSION.tgz solr-$SOLR_VERSION/bin/install_solr_service.sh --strip-components=2 && \
    ./install_solr_service.sh solr-$SOLR_VERSION.tgz && \
    systemctl disable solr

RUN wget -q -O - https://cpanmin.us | perl - App::cpanminus && \
    cpanm Carton JSON::XS

ENV MB_SOLR_TAG v3.1.2

# Steps taken from https://github.com/metabrainz/mb-solr/blob/master/Dockerfile
RUN sudo -E -H -u musicbrainz git clone --recursive https://github.com/metabrainz/mb-solr.git && \
    cd mb-solr && \
    git checkout $MB_SOLR_TAG && \
    cd mmd-schema/brainz-mmd2-jaxb && \
    mvn install && \
    cd ../../mb-solr && \
    mvn package -DskipTests && \
    mkdir -p /opt/solr/lib $SOLR_HOME && \
    cp target/mb-solr-0.0.1-SNAPSHOT-jar-with-dependencies.jar /opt/solr/lib/ && \
    cd .. && \
    cp -R mbsssss $SOLR_HOME/mycores/ && \
    sed -i'' 's|</solr>|<str name="sharedLib">/opt/solr/lib</str></solr>|' $SOLR_HOME/solr.xml && \
    mkdir $SOLR_HOME/data && \
    chown -R solr:solr /opt/solr/ && \
    cd /home/musicbrainz

ENV SIR_COMMIT 7c4c50b

RUN sudo -E -H -u musicbrainz git clone https://github.com/metabrainz/sir.git && \
    cd sir && \
    sudo -E -H -u musicbrainz git reset --hard $SIR_COMMIT && \
    sudo -E -H -u musicbrainz sh -c 'virtualenv --python=python2 venv; . venv/bin/activate; pip install -r requirements.txt' && \
    cd /home/musicbrainz

RUN curl -sLO https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip && \
    unzip chromedriver_linux64.zip -d /usr/local/bin && \
    chmod +x /usr/local/bin/chromedriver && \
    rm chromedriver_linux64.zip

RUN curl -sLO https://github.com/validator/validator/releases/download/18.11.5/vnu.jar_18.11.5.zip && \
    unzip -d vnu -j vnu.jar_18.11.5.zip && \
    rm vnu.jar_18.11.5.zip

RUN echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen && \
    locale-gen

ENV PGDATA /home/musicbrainz/pgdata

RUN pg_dropcluster --stop 10 main && \
    pg_createcluster --datadir="$PGDATA" --encoding=utf8 --locale=en_US.UTF-8 --user=postgres 10 main

COPY --chown=postgres:postgres \
    docker/musicbrainz-tests/pg_hba.conf \
    docker/musicbrainz-tests/postgresql.conf \
    $PGDATA/

RUN sudo -E -H -u postgres touch \
    $PGDATA/pg_ident.conf

COPY docker/musicbrainz-tests/sir-config.ini sir/config.ini

COPY \
    docker/musicbrainz-tests/chrome.service \
    /etc/service/chrome/run
COPY \
    docker/musicbrainz-tests/postgresql.service \
    /etc/service/postgresql/run
COPY \
    docker/musicbrainz-tests/redis.service \
    /etc/service/redis/run
COPY \
    docker/musicbrainz-tests/sir-queue-purger.service \
    /etc/service/sir-queue-purger/run
COPY \
    docker/musicbrainz-tests/solr.service \
    /etc/service/solr/run
COPY \
    docker/scripts/start_template_renderer.sh \
    /etc/service/template-renderer/run
COPY \
    docker/musicbrainz-tests/vnu.service \
    /etc/service/vnu/run
COPY \
    docker/musicbrainz-tests/website.service \
    /etc/service/website/run
RUN chmod 755 \
        /etc/service/chrome/run \
        /etc/service/postgresql/run \
        /etc/service/redis/run \
        /etc/service/sir-queue-purger/run \
        /etc/service/solr/run \
        /etc/service/template-renderer/run \
        /etc/service/vnu/run \
        /etc/service/website/run
RUN touch \
    /etc/service/chrome/down \
    /etc/service/postgresql/down \
    /etc/service/redis/down \
    /etc/service/sir-queue-purger/down \
    /etc/service/solr/down \
    /etc/service/template-renderer/down \
    /etc/service/vnu/down \
    /etc/service/website/down

LABEL com.circleci.preserve-entrypoint=true
