#!/bin/sh

cd /home/musicbrainz/artwork-indexer

export HOME=/home/musicbrainz
exec chpst -u musicbrainz:musicbrainz \
    env PATH="/home/musicbrainz/.local/bin:$PATH" \
    poetry run python indexer.py --config=config.selenium.ini --max-wait=1 2>&1
