-- Generated by CompileSchemaScripts.pl from:
-- 20141226-geodesic-extension.sql
\set ON_ERROR_STOP 1
BEGIN;
SET search_path = musicbrainz, public;
--------------------------------------------------------------------------------
SELECT '20141226-geodesic-extension.sql';

CREATE EXTENSION IF NOT EXISTS earthdistance WITH SCHEMA public;
COMMIT;
