-- Generated by CompileSchemaScripts.pl from:
-- 20180503-mbs-9708-drop-area-containment-view.sql
-- 20190422-mbs-7480.sql
-- 20190422-mbs-9428-collection-collaborators.sql
\set ON_ERROR_STOP 1
BEGIN;
SET search_path = musicbrainz, public;
SET LOCAL statement_timeout = 0;
--------------------------------------------------------------------------------
SELECT '20180503-mbs-9708-drop-area-containment-view.sql';

DROP VIEW area_containment;

--------------------------------------------------------------------------------
SELECT '20190422-mbs-7480.sql';

ALTER TABLE cover_art_archive.cover_art ADD COLUMN filesize INTEGER;
ALTER TABLE cover_art_archive.cover_art ADD COLUMN thumb_250_filesize INTEGER;
ALTER TABLE cover_art_archive.cover_art ADD COLUMN thumb_500_filesize INTEGER;
ALTER TABLE cover_art_archive.cover_art ADD COLUMN thumb_1200_filesize INTEGER;

--------------------------------------------------------------------------------
SELECT '20190422-mbs-9428-collection-collaborators.sql';

CREATE TABLE editor_collection_collaborator (
    collection INTEGER NOT NULL, -- PK, references editor_collection.id
    editor INTEGER NOT NULL -- references editor.id
);

ALTER TABLE editor_collection_collaborator ADD CONSTRAINT editor_collection_collaborator_pkey PRIMARY KEY (collection, editor);

COMMIT;
