-- Generated by CompileSchemaScripts.pl from:
-- 20180503-mbs-9708-drop-area-containment-view.sql
-- 20190422-mbs-7480.sql
-- 20190422-mbs-9973-collection-added-date.sql
-- 20190422-mbs-9428-collection-collaborators.sql
-- 20190422-mbs-5818-collection-position.sql
-- 20190422-mbs-1658-collection-text.sql
\set ON_ERROR_STOP 1
BEGIN;
SET search_path = musicbrainz, public;
SET LOCAL statement_timeout = 0;
--------------------------------------------------------------------------------
SELECT '20180503-mbs-9708-drop-area-containment-view.sql';

DROP VIEW area_containment;

--------------------------------------------------------------------------------
SELECT '20190422-mbs-7480.sql';

ALTER TABLE cover_art_archive.cover_art ADD COLUMN filesize INTEGER;
ALTER TABLE cover_art_archive.cover_art ADD COLUMN thumb_250_filesize INTEGER;
ALTER TABLE cover_art_archive.cover_art ADD COLUMN thumb_500_filesize INTEGER;
ALTER TABLE cover_art_archive.cover_art ADD COLUMN thumb_1200_filesize INTEGER;

--------------------------------------------------------------------------------
SELECT '20190422-mbs-9973-collection-added-date.sql';

ALTER TABLE editor_collection_area ADD COLUMN added TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE editor_collection_artist ADD COLUMN added TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE editor_collection_event ADD COLUMN added TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE editor_collection_instrument ADD COLUMN added TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE editor_collection_label ADD COLUMN added TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE editor_collection_place ADD COLUMN added TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE editor_collection_recording ADD COLUMN added TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE editor_collection_release ADD COLUMN added TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE editor_collection_release_group ADD COLUMN added TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE editor_collection_series ADD COLUMN added TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE editor_collection_work ADD COLUMN added TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE editor_collection_deleted_entity ADD COLUMN added TIMESTAMP WITH TIME ZONE DEFAULT NOW();

UPDATE editor_collection_area SET added = NULL;
UPDATE editor_collection_artist SET added = NULL;
UPDATE editor_collection_event SET added = NULL;
UPDATE editor_collection_instrument SET added = NULL;
UPDATE editor_collection_label SET added = NULL;
UPDATE editor_collection_place SET added = NULL;
UPDATE editor_collection_recording SET added = NULL;
UPDATE editor_collection_release SET added = NULL;
UPDATE editor_collection_release_group SET added = NULL;
UPDATE editor_collection_series SET added = NULL;
UPDATE editor_collection_work SET added = NULL;
UPDATE editor_collection_deleted_entity SET added = NULL;

--------------------------------------------------------------------------------
SELECT '20190422-mbs-9428-collection-collaborators.sql';

CREATE TABLE editor_collection_collaborator (
    collection INTEGER NOT NULL, -- PK, references editor_collection.id
    editor INTEGER NOT NULL -- references editor.id
);

ALTER TABLE editor_collection_collaborator ADD CONSTRAINT editor_collection_collaborator_pkey PRIMARY KEY (collection, editor);

--------------------------------------------------------------------------------
SELECT '20190422-mbs-5818-collection-position.sql';

ALTER TABLE editor_collection_area ADD COLUMN position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0);
ALTER TABLE editor_collection_artist ADD COLUMN position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0);
ALTER TABLE editor_collection_event ADD COLUMN position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0);
ALTER TABLE editor_collection_instrument ADD COLUMN position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0);
ALTER TABLE editor_collection_label ADD COLUMN position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0);
ALTER TABLE editor_collection_place ADD COLUMN position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0);
ALTER TABLE editor_collection_recording ADD COLUMN position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0);
ALTER TABLE editor_collection_release ADD COLUMN position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0);
ALTER TABLE editor_collection_release_group ADD COLUMN position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0);
ALTER TABLE editor_collection_series ADD COLUMN position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0);
ALTER TABLE editor_collection_work ADD COLUMN position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0);
ALTER TABLE editor_collection_deleted_entity ADD COLUMN position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0);

--------------------------------------------------------------------------------
SELECT '20190422-mbs-1658-collection-text.sql';

ALTER TABLE editor_collection_area ADD COLUMN comment TEXT DEFAULT '' NOT NULL;
ALTER TABLE editor_collection_artist ADD COLUMN comment TEXT DEFAULT '' NOT NULL;
ALTER TABLE editor_collection_event ADD COLUMN comment TEXT DEFAULT '' NOT NULL;
ALTER TABLE editor_collection_instrument ADD COLUMN comment TEXT DEFAULT '' NOT NULL;
ALTER TABLE editor_collection_label ADD COLUMN comment TEXT DEFAULT '' NOT NULL;
ALTER TABLE editor_collection_place ADD COLUMN comment TEXT DEFAULT '' NOT NULL;
ALTER TABLE editor_collection_recording ADD COLUMN comment TEXT DEFAULT '' NOT NULL;
ALTER TABLE editor_collection_release ADD COLUMN comment TEXT DEFAULT '' NOT NULL;
ALTER TABLE editor_collection_release_group ADD COLUMN comment TEXT DEFAULT '' NOT NULL;
ALTER TABLE editor_collection_series ADD COLUMN comment TEXT DEFAULT '' NOT NULL;
ALTER TABLE editor_collection_work ADD COLUMN comment TEXT DEFAULT '' NOT NULL;
ALTER TABLE editor_collection_deleted_entity ADD COLUMN comment TEXT DEFAULT '' NOT NULL;

COMMIT;
