-- Generated by CompileSchemaScripts.pl from:
-- 20211203-mbs-11312-standalone.sql
\set ON_ERROR_STOP 1
BEGIN;
SET search_path = musicbrainz, public;
SET LOCAL statement_timeout = 0;
--------------------------------------------------------------------------------
SELECT '20211203-mbs-11312-standalone.sql';


-- Foreign keys

ALTER TABLE edit_note_change
   ADD CONSTRAINT edit_note_change_fk_edit_note
   FOREIGN KEY (edit_note)
   REFERENCES edit_note(id);

ALTER TABLE edit_note_change
   ADD CONSTRAINT edit_note_change_fk_change_editor
   FOREIGN KEY (change_editor)
   REFERENCES editor(id);

COMMIT;
