-- Generated by CompileSchemaScripts.pl from:
-- 20240223-mbs-13421-fks.sql
-- 20240319-mbs-13514.sql
\set ON_ERROR_STOP 1
BEGIN;
SET search_path = musicbrainz, public;
SET LOCAL statement_timeout = 0;
--------------------------------------------------------------------------------
SELECT '20240223-mbs-13421-fks.sql';

ALTER TABLE editor_collection_type -- Already dropped in mirror update script
      ADD CONSTRAINT allowed_collection_entity_type CHECK (
          entity_type IN ('area', 'artist', 'event', 'genre', 'instrument', 'label', 'place', 'recording', 'release', 'release_group', 'series', 'work')
      );

ALTER TABLE editor_collection_genre
   ADD CONSTRAINT editor_collection_genre_fk_collection
     FOREIGN KEY (collection)
     REFERENCES editor_collection(id),
   ADD CONSTRAINT editor_collection_genre_fk_genre
     FOREIGN KEY (genre)
     REFERENCES genre(id);

--------------------------------------------------------------------------------
SELECT '20240319-mbs-13514.sql';


ALTER TABLE label ADD CONSTRAINT label_code_length CHECK (label_code > 0 AND label_code < 1000000);

COMMIT;
