-- Generated by CompileSchemaScripts.pl from:
-- 20250320-mbs-13768-fks.sql
\set ON_ERROR_STOP 1
BEGIN;
SET search_path = musicbrainz, public;
SET LOCAL statement_timeout = 0;
--------------------------------------------------------------------------------
SELECT '20250320-mbs-13768-fks.sql';

SET search_path = musicbrainz;


ALTER TABLE medium_gid_redirect
   ADD CONSTRAINT medium_gid_redirect_fk_new_id
   FOREIGN KEY (new_id)
   REFERENCES medium(id);

COMMIT;
