-- Generated by CompileSchemaScripts.pl from:
-- 20260212-mbs-14252.sql
\set ON_ERROR_STOP 1
BEGIN;
SET search_path = musicbrainz, public;
SET LOCAL statement_timeout = 0;
--------------------------------------------------------------------------------
SELECT '20260212-mbs-14252.sql';


ALTER TABLE isrc DROP COLUMN source CASCADE;
ALTER TABLE iswc DROP COLUMN source CASCADE;

COMMIT;
