-- Generated by CompileSchemaScripts.pl from:
-- 20260121-mbs-14092-fks.sql
\set ON_ERROR_STOP 1
BEGIN;
SET search_path = musicbrainz, public;
SET LOCAL statement_timeout = 0;
--------------------------------------------------------------------------------
SELECT '20260121-mbs-14092-fks.sql';

------------------
-- constraints  --
------------------

ALTER TABLE series_type ADD CONSTRAINT allowed_series_entity_type
  CHECK (
    entity_type IN (
      'artist',
      'event',
      'recording',
      'release',
      'release_group',
      'series',
      'work'
    )
  );

COMMIT;
