-- Generated by CompileSchemaScripts.pl from:
-- 20260121-mbs-14092-fks.sql
-- 20260422-mbs-6551-master_and_standalone.sql
\set ON_ERROR_STOP 1
BEGIN;
SET search_path = musicbrainz, public;
SET LOCAL statement_timeout = 0;
--------------------------------------------------------------------------------
SELECT '20260121-mbs-14092-fks.sql';

------------------
-- constraints  --
------------------

ALTER TABLE series_type ADD CONSTRAINT allowed_series_entity_type
  CHECK (
    entity_type IN (
      'artist',
      'event',
      'recording',
      'release',
      'release_group',
      'series',
      'work'
    )
  );

--------------------------------------------------------------------------------
SELECT '20260422-mbs-6551-master_and_standalone.sql';


ALTER TABLE release_label
  ADD CONSTRAINT no_empty_string_catalog_number
  CHECK (catalog_number != '');

ALTER TABLE release_label
  ADD CONSTRAINT release_label_uniq
  UNIQUE NULLS NOT DISTINCT (release, label, catalog_number)
  DEFERRABLE INITIALLY DEFERRED;

COMMIT;
