-- Generated by CompileSchemaScripts.pl from:
-- 20260602-new-sitemaps-indexes.sql
-- 20260623-mbs-12379.sql
-- 20260723-mbs-14386.sql
\set ON_ERROR_STOP 1
BEGIN;
SET search_path = musicbrainz, public;
SET LOCAL statement_timeout = 0;
--------------------------------------------------------------------------------
SELECT '20260602-new-sitemaps-indexes.sql';


CREATE INDEX artist_lastmod_idx_id ON sitemaps.artist_lastmod (id);
CREATE INDEX label_lastmod_idx_id ON sitemaps.label_lastmod (id);
CREATE INDEX place_lastmod_idx_id ON sitemaps.place_lastmod (id);
CREATE INDEX recording_lastmod_idx_id ON sitemaps.recording_lastmod (id);
CREATE INDEX release_lastmod_idx_id ON sitemaps.release_lastmod (id);
CREATE INDEX release_group_lastmod_idx_id ON sitemaps.release_group_lastmod (id);
CREATE INDEX work_lastmod_idx_id ON sitemaps.work_lastmod (id);

--------------------------------------------------------------------------------
SELECT '20260623-mbs-12379.sql';

CREATE INDEX IF NOT EXISTS annotation_idx_editor ON annotation (editor);
CREATE INDEX IF NOT EXISTS autoeditor_election_vote_idx_voter ON autoeditor_election_vote (voter);
CREATE INDEX IF NOT EXISTS editor_idx_deleted ON editor (id) WHERE deleted;

--------------------------------------------------------------------------------
SELECT '20260723-mbs-14386.sql';

-----------------------------------
-- UPDATE VIEW TO USE RIGHT GID  --
-----------------------------------

CREATE OR REPLACE VIEW series_series AS
    SELECT entity0 AS series_part,
           entity1 AS series,
           lss.id AS relationship,
           link_order,
           lss.link,
           COALESCE(text_value, '') AS text_value
    FROM l_series_series lss
    JOIN series s ON s.id = lss.entity1
    JOIN link l ON l.id = lss.link
    JOIN link_type lt ON (lt.id = l.link_type AND lt.gid = '8fe04b66-fe39-40ce-a28f-76b816d3f55a')
    LEFT OUTER JOIN link_attribute_text_value latv ON (latv.attribute_type = 788 AND latv.link = l.id)
    ORDER BY series, link_order;

COMMIT;
