BEGIN;

ALTER TABLE artist ALTER COLUMN comment SET NOT NULL;
ALTER TABLE artist ALTER COLUMN comment SET DEFAULT '';

ALTER TABLE label ALTER COLUMN comment SET NOT NULL;
ALTER TABLE label ALTER COLUMN comment SET DEFAULT '';

ALTER TABLE recording ALTER COLUMN comment SET NOT NULL;
ALTER TABLE recording ALTER COLUMN comment SET DEFAULT '';

ALTER TABLE release ALTER COLUMN comment SET NOT NULL;
ALTER TABLE release ALTER COLUMN comment SET DEFAULT '';

ALTER TABLE release_raw ALTER COLUMN comment SET NOT NULL;
ALTER TABLE release_raw ALTER COLUMN comment SET DEFAULT '';

ALTER TABLE release_group ALTER COLUMN comment SET NOT NULL;
ALTER TABLE release_group ALTER COLUMN comment SET DEFAULT '';

ALTER TABLE work ALTER COLUMN comment SET NOT NULL;
ALTER TABLE work ALTER COLUMN comment SET DEFAULT '';

ALTER TABLE artist_credit_name ALTER COLUMN join_phrase SET NOT NULL;
ALTER TABLE artist_credit_name ALTER COLUMN join_phrase SET DEFAULT '';

COMMIT;
