#!/bin/bash
echo starting
exec 2>&1
set -e
cd mb_server
umask 022
exec \
    setuidgid musicbrainz carton exec -- \
        plackup -Ilib \
            -s FastCGI \
            -E deployment \
            --port 55901 \
            --nproc 5 \
            --pid fcgi.pid \
            --keeperr

