#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use Getopt::Long qw( GetOptions );
use Pod::Usage qw( pod2usage );

use DBDefs;
use MusicBrainz::Server::Context;
use Sql;

my $cleartext = 0;
my $database = 'MAINTENANCE';
my $show_help = 0;

GetOptions(
    'cleartext!' => \$cleartext,
    'database=s' => \$database,
    'help' => \$show_help,
) or exit 2;

pod2usage() if $show_help;
pod2usage(
    -exitval => 64, # EX_USAGE
    -message => "$0: missing arguments",
) unless scalar(@ARGV) == 1;

die 'This script may only be run with `LOCAL_ACCOUNTS_ENABLED` set in lib/DBDefs.pm.'
    unless DBDefs->LOCAL_ACCOUNTS_ENABLED;

my $c = MusicBrainz::Server::Context->create_script_context(
    database => $database,
);

my $username = $ARGV[0];
my $editor = $c->model('Editor')->get_by_name($username);
die 'User not found.' unless defined $editor;

print 'Password: ';
my $password = <STDIN>;
chomp $password;

if ($cleartext) {
    Sql::run_in_transaction(sub {
        $c->sql->do(<<~'SQL', "{CLEARTEXT}$password", $username);
            UPDATE editor
               SET password = ?
             WHERE lower(name) = lower(?)
            SQL
    }, $c->sql);
} else {
    $c->model('Editor')->update_password($username, $password);
}
print 'Password changed.';

__END__

=head1 NAME

ChangePassword - Change the password of a local account

=head1 SYNOPSIS

ChangePassword [options] [username]

Options:

   --cleartext       store the password as cleartext (default: disabled)
   --database        database to use (default: MAINTENANCE)
   --help            show this help

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2026 MetaBrainz Foundation

This file is part of MusicBrainz, the open internet music database,
and is licensed under the GPL version 2, or (at your option) any
later version: http://www.gnu.org/licenses/gpl-2.0.txt

=cut
