#!/usr/bin/env bash

set -o errexit

MB_SERVER_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../" && pwd)
cd "$MB_SERVER_ROOT"

source admin/config.sh

TEMP_DIR=$1 ; shift

# Was a replication packet created?
shopt -s nullglob
REPLICATION_FILE=`echo -n "$TEMP_DIR"/replication-*.tar.bz2`
REPLICATION_FILE_ASC=`echo -n "$TEMP_DIR"/replication-*.tar.bz2.asc`
shopt -u nullglob

# Replication data, if any, goes to both the backup directory and the
# FTP directory.
if [ "$REPLICATION_FILE" ]
then
    echo `date`" : Copying replication packet to backup dir"
    chown "$BACKUP_USER:$BACKUP_GROUP" "$TEMP_DIR"/replication-*.tar.bz2
    chmod "$BACKUP_FILE_MODE" "$TEMP_DIR"/replication-*.tar.bz2
    cp -a "$TEMP_DIR"/replication-*.tar.bz2 "$BACKUP_DIR"/replication/
    if [ "$REPLICATION_FILE_ASC" ]
    then
        cp -a "$TEMP_DIR"/replication-*.tar.bz2.asc "$BACKUP_DIR"/replication/
    fi

    echo `date`" : Copying replication packet to FTP dir"
    chown "$FTP_USER:$FTP_GROUP" "$TEMP_DIR"/replication-*.tar.bz2
    chmod "$FTP_FILE_MODE" "$TEMP_DIR"/replication-*.tar.bz2
    mv "$TEMP_DIR"/replication-*.tar.bz2 "$FTP_DATA_DIR"/replication/
    if [ "$REPLICATION_FILE_ASC" ]
    then
        mv "$TEMP_DIR"/replication-*.tar.bz2.asc "$FTP_DATA_DIR"/replication/
    fi
fi

# eof
