#!/usr/bin/env perl
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use MooseX::Runnable::Run;
run_application 'MusicBrainz::Script::SampleDataDump', @ARGV;

=head1 SYNOPSIS

This script will generate a sample database dump useful for testing purposes,
with the goal of containing a useful sampling of every entity type. Currently,
the script dumps the following three artists, along with all releases,
recordings, and works related to them:

 * b7ffd2af-418f-4be2-bdd1-22f8b48613da (Nine Inch Nails)
 * 1d11e2a1-4531-4d61-a8c7-7b5c6a608fd2 (Ice Cube)
 * c278de2c-9696-4fdf-a919-0781cd945e2c (Игорь Стравинский)

Options:

    --help                      show this help
    --database                  database to dump from (default: READWRITE)
    --output-dir                location where the dump is outputted
                                (default: .)

=cut

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2017 MetaBrainz Foundation

This file is part of MusicBrainz, the open internet music database,
and is licensed under the GPL version 2, or (at your option) any
later version: http://www.gnu.org/licenses/gpl-2.0.txt

=cut
