#!/home/httpd/musicbrainz/mb_server/cgi-bin/perl -w
#____________________________________________________________________________
#
#   MusicBrainz -- the open internet music database
#
#   Copyright (C) 1998 Robert Kaye
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   $Id$
#____________________________________________________________________________

use strict;

use FindBin;
use lib "$FindBin::Bin/../cgi-bin";

use DBDefs;
use MusicBrainz;
use Sql;
use UserStuff;

my $mb = MusicBrainz->new;
$mb->Login;
my $sql = Sql->new($mb->{DBH});

my $name = shift;
my $us = UserStuff->new($mb->{DBH});

my $user = $us->newFromName($name)
	or die "No such user '$name'\n";

warn "$name is already an automod\n"
	if $us->IsAutoMod($user->GetPrivs);

$sql->Begin;

$user->SetPrivs($user->GetPrivs | $user->AUTOMOD_FLAG);
$sql->Do("UPDATE moderator SET privs = ? WHERE id = ?", $user->GetPrivs, $user->GetId);

# which mod types get automodded?
require Moderation;
my $mod = Moderation->new($mb->{DBH});
my @autotypes = grep { $mod->IsAutoModType($_) } values %{ ModDefs->type_as_hashref };
print "at=@autotypes\n";
my $types = join ",", @autotypes;

my $n = $sql->Do("UPDATE moderation_open SET yesvotes = 100 WHERE
	moderator = ? AND type IN ($types)", $user->GetId);
print "Set yesvotes=100 for $n mods\n";

$sql->Commit;

# eof
