#!/usr/bin/env perl

use warnings;

# Given a database connection key, this script simply exec's "psql" with the
# appropriate args.

use strict;

use FindBin;
use lib "$FindBin::Bin/../lib";

use strict;
use DBDefs;
use Getopt::Long;

use aliased 'MusicBrainz::Server::DatabaseConnectionFactory' => 'Databases';

my $system = 0;
my $help = 0;

GetOptions(
    'system'    => \$system,
    'help'      => \$help,
) or exit 2;

my $key = shift // 'READWRITE';

if ($help) {
    die "Usage: psql [database]\n\n  database -- the DBDefs name of the database to connect to. (default is READWRITE)\n";
}

my $db = Databases->get($key) or die "No such database '$key'\n";

if ($system) {
    my $sys_db = Databases->get('SYSTEM');
    $db = $db->meta->clone_object($sys_db, database => $db->database);
}

$ENV{'PGPASSWORD'} = $db->password;

exec 'psql', $db->shell_args, @ARGV;

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2002 Robert Kaye

This file is part of MusicBrainz, the open internet music database,
and is licensed under the GPL version 2, or (at your option) any
later version: http://www.gnu.org/licenses/gpl-2.0.txt

=cut
