#!/usr/bin/perl -w
# vi: set ts=4 sw=4 :
#____________________________________________________________________________
#
#   MusicBrainz -- the open internet music database
#
#   Copyright (C) 2002 Robert Kaye
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   $Id$
#____________________________________________________________________________

# Given a database connection key, this script simply exec's "psql" with the
# appropriate args.

use FindBin;
use lib "$FindBin::Bin/../lib";

use strict;
use DBDefs;
use Getopt::Long;

my $profile;
my $system = 0;

GetOptions(
    "system"    => \$system,
    "profile=s" => \$profile
) or exit 2;

my $key = shift;
my $db = MusicBrainz::Server::Database->get($key)
	or die "No such database '$key'\n";

if ($system) {
    my $sys_db = MusicBrainz::Server::Database->get("SYSTEM");
    $db = $sys_db->modify(database => $db->database);
}

if (defined $profile && $profile eq "test") {
    $ENV{"PGOPTIONS"} = "-c search_path=musicbrainz_test";
}

exec "psql", $db->shell_args;

# eof psql
