#!/usr/bin/perl -w
#____________________________________________________________________________
#
#	MusicBrainz -- the open music metadata database
#
#	Copyright (C) 2001 Robert Kaye
#
#	This program is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; either version 2 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program; if not, write to the Free Software
#	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#	$Id: Sql.pm 9606 2007-11-24 16:14:09Z luks $
#____________________________________________________________________________


use strict;

use FindBin;
use lib "$FindBin::Bin/../cgi-bin";

use MusicBrainz::Server::CollectionInfo;
use MusicBrainz::Server::Release;
use Data::Dumper;


# login
require MusicBrainz;
my $mbraw = MusicBrainz->new();
$mbraw->Login(db => 'RAWDATA');
my $mbro = MusicBrainz->new();
$mbro->Login();


# set up SQL identifiers
my $sqlraw = Sql->new($mbraw->{DBH});
my $sqlro = Sql->new($mbro->{DBH});


# select all collections that shall receive notifications by e-mail
my $collections = $sqlraw->SelectSingleColumnArray('SELECT id FROM collection_info WHERE emailnotifications = TRUE');

print 'collections:'.Dumper($collections);

# iterate over all collections to be notified and send out e-mails(if any new releases)
foreach my $currentCollectionId (@$collections)
{
	my $currentPreferences = undef;
	my $currentCollection = MusicBrainz::Server::CollectionInfo->newFromCollectionId($currentCollectionId, $mbro->{DBH}, $mbraw->{DBH}, $currentPreferences);
	
	my $newReleases = $currentCollection->GetNewReleases();
	
	my $count = @{$newReleases};
	
	#print Dumper($newReleases);
	
	my $userId = $currentCollection->GetUserId();
	
	if($count>0) # notifications should be sent
	{
		sendMail($currentCollection, $newReleases, $userId, $mbro->{DBH});
	}
}


exit 1;


sub sendMail
{
	my ($collectionId, $releaseIds, $userId, $rodbh) = @_;
	
	#my $user = UserStuff->newFromId();
	
	print Dumper(@$releaseIds);
	my $subject = 'New releases';
	my $message = 'The following releases are about to be released:\n';
	
	
	for my $releaseId (@{$releaseIds})
	{
		my $release = MusicBrainz::Server::Release->new($rodbh);
		$release->SetId($releaseId);
		$release->LoadFromId();
		
		$message = $message . $release->GetName() . '\n';
		
		
		
		
		require UserStuff;
		my $user = UserStuff->new($rodbh);
		$user = $user->newFromId($userId);
		


		require MusicBrainz::Server::Mail;
		my $mail = MusicBrainz::Server::Mail->new(
			# Sender: not required
			From		=> 'MusicBrainz Collection Robot <noreply@musicbrainz.org>',
			# To: $user (automatic)
			"Reply-To"	=> 'MusicBrainz Support <support@musicbrainz.org>',
			Subject		=> "New releases",
			Type		=> "text/plain",
			Encoding	=> "quoted-printable",
			Data		=> $message,
		);
	    $mail->attr("content-type.charset" => "utf-8");

	
		$user->SendFormattedEmail(entity => $mail);
	}
	
	
	print $message;
}


=head1 NAME
	SendReleaseNotifications - Send e-mail notifications about new releases
	
	=head1 DESCRIPTION
	Iterate over all users who have selected to have e-mail notifications sent and notify them by email about new releases.

	=cut