#!/usr/bin/env perl

use warnings;
#____________________________________________________________________________
#
#   MusicBrainz -- the open internet music database
#
#   Copyright (C) 1998 Robert Kaye
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   $Id$
#____________________________________________________________________________

use strict;

use FindBin;
use lib "$FindBin::Bin/../lib";

use DBDefs;
chdir DBDefs->MB_SERVER_ROOT or die $!;
chdir "root/static" or die $!;

vRefreshImportedStyleSheets("main.css");

sub vRefreshImportedStyleSheets
{
    my $file = shift;

    use IO::File;
    my $in = IO::File->new($file, O_RDONLY) or die "open $file: $!";

    my $all = do { local $/; <$in> };
    my $old = $all;
    $all =~ s/(\@import url\()(.*?)(\))/
        $1 . update_file_link($2, $file) .  $3
        /eg;
    
    return 0 if $all eq $old;
    close $in;

    #print "Write to $file:\n$all";
    use File::Temp qw( tempfile );
    use File::Basename qw( dirname );
    my ($fh, $name) = tempfile(
        "tmpcss-XXXXXXXX",
        DIR => dirname($file),
        CLEANUP => 1,
    ) or die $!;
    eval 'END { unlink $name if defined $name }';

    print $fh $all;
    close $fh or die $!;
    chmod 0644, $name or warn $!;
    rename $name => $file or warn $!;
    $name = undef;

    print "Updated $file\n";

    1;
}

sub update_file_link
{
    my ($link_to, $link_from) = @_;
    # TODO take care of the paths in $link_to and $link_from

    my $existing_time = 0;
    $existing_time = hex $1
        if $link_to =~ s/\?t=(\w{8})$//;
    
    vRefreshImportedStyleSheets($link_to);

    my $t = (stat $link_to)[9];
    "$link_to?t=" . sprintf "%08X", $t;
}

# eof UpdateStyleSheetLinks
