#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")/../"

./node_modules/.bin/eslint \
    --no-eslintrc \
    --env 'browser,node,es2020' \
    --parser '@babel/eslint-parser' \
    --plugin react \
    --plugin flowtype \
    --plugin import \
    --plugin react-hooks \
    --global '__webpack_public_path__:true' \
    --global __DEV__ \
    --global GLOBAL_JS_NAMESPACE \
    --global '$' \
    --global jQuery \
    --global addColon \
    --global addColonText \
    --global hasOwnProp \
    --global hyphenateTitle \
    --global nonEmpty \
    --global l \
    --global ln \
    --global lp \
    --global N_l \
    --global N_ln \
    --global N_lp \
    --global exp \
    --global texp \
    --global l_attributes \
    --global ln_attributes \
    --global lp_attributes \
    --global l_countries \
    --global ln_countries \
    --global lp_countries \
    --global l_instrument_descriptions \
    --global ln_instrument_descriptions \
    --global lp_instrument_descriptions \
    --global l_instruments \
    --global ln_instruments \
    --global lp_instruments \
    --global l_languages \
    --global ln_languages \
    --global lp_languages \
    --global l_relationships \
    --global ln_relationships \
    --global lp_relationships \
    --global l_scripts \
    --global ln_scripts \
    --global lp_scripts \
    --global l_statistics \
    --global ln_statistics \
    --global lp_statistics \
    --rule 'react/jsx-uses-vars: warn' \
    --rule 'flowtype/define-flow-type: warn' \
    --rule 'flowtype/use-flow-type: warn' \
    --rule \
    "$@"
