#!/usr/bin/env perl

use utf8;
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use DBDefs;
use Sql;
use aliased 'MusicBrainz::Server::DatabaseConnectionFactory' => 'Databases';

if ($ARGV[0])
{
    my $db = Databases->get_connection(uc($ARGV[0]));

    my $sql = Sql->new( $db->conn );

    my $so = $sql->select_single_value(
        'SELECT TRUE FROM information_schema.information_schema_catalog_name WHERE catalog_name = ?',
        $db->database->database);
    exit 0 if $so;
    exit 1; # E_NODATABASE
}
else
{
    print "Usage: database_exists <DBNAME>\n";
    print "\n";
    print "\tDBNAME\tThe database name (READWRITE or TEST)\n";
    print "\n";
    exit 2;
}

