#!/bin/bash

BASEDIR=$(dirname $0)/..

TT_DIR=$BASEDIR/root
I18N_DIR=$BASEDIR/po

find $TT_DIR -iname *.tt > $I18N_DIR/POTFILES.in 
#xgettext.pl -o $I18N_DIR/messages.pot -g -P tt2 -u -w -f $I18N_DIR/POTFILES.in 

xgettext -o $I18N_DIR/messages.pot -f $I18N_DIR/POTFILES.in --language=php --keyword --keyword=l:1 --keyword=ln:1,2

for i in $I18N_DIR/*.po
do
    msgmerge -U $i $I18N_DIR/messages.pot
    msgfmt $i --statistics -o $I18N_DIR/$(basename $i .po).mo
done