#!/usr/bin/perl -w
# vi: set ts=4 sw=4 :
#____________________________________________________________________________
#
#    MusicBrainz -- the open internet music database
#
#    Copyright (C) 1998 Robert Kaye
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#    $Id$
#____________________________________________________________________________

use FindBin;
use lib "$FindBin::Bin/../../lib";

use strict;
use DBDefs;
use Sql;
use Data::Dumper;
use MusicBrainz;
use MusicBrainz::Server::Artist;

my $mb = MusicBrainz->new;
$mb->Login;
my $sql = Sql->new($mb->{dbh});

$sql->Begin();
my ($ent0, $ent1, $rel, $rem, $line);
while(defined($line = <>))
{
    $line =~ s/\s*$//g;
    next if (!$line);
    next if ($line =~ /^#/);

    ($ent0, $ent1, $rel, $rem) = split ',', $line;
    $ent0 =~ s/^\s*|\s*$//g;
    $ent1 =~ s/^\s*|\s*$//g;
    $rel =~ s/^\s*|\s*$//g;
#print "$ent0 $ent1 $rel\n";

    my $ar0 = MusicBrainz::Server::Artist->new($mb->{dbh});
    my $ar1 = MusicBrainz::Server::Artist->new($mb->{dbh});
    $ar0->SetMBId($ent0);
    $ar1->SetMBId($ent1);

    if ($ar0->LoadFromId())
    {
        if ($ar1->LoadFromId())
        {
                my $id;

                $id = "4" if ($rel eq 'alias');
                $id = "2" if ($rel eq 'member');
                $id = "3" if ($rel eq 'collaboration');
                ($ar0, $ar1) = ($ar1, $ar0) if ($rel eq 'collaboration');
                die if not $id;

                $sql->Do("INSERT INTO l_artist_artist (link0, link1, link_type, begindate, enddate) values (?, ?, ?, '', '')",
                             $ar0->GetId, $ar1->GetId, $id);
        }
        else
        {
                print "$line\n";
                next;
        }
    }
    else
    {
        print "$line\n";
        next;
    }

}
$sql->Commit();
