#!/bin/sh

cd /home/musicbrainz/artwork-redirect

export HOME=/home/musicbrainz
exec chpst -u musicbrainz:musicbrainz \
    env PATH="/home/musicbrainz/.local/bin:$PATH" \
    uv run python artwork_redirect_server.py \
    2>&1
