#!/usr/bin/env perl

use warnings;
# vi: set ts=4 sw=4 :
#____________________________________________________________________________
#
#   MusicBrainz -- the open internet music database
#
#   Copyright (C) 1998 Robert Kaye
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   $Id: BadWin32CDTOCs 8551 2006-10-19 20:10:48Z robert $
#____________________________________________________________________________

use FindBin;
use lib "$FindBin::Bin/../../lib";

use strict;
use warnings;

package BadAmazonURLs;
use base qw( MusicBrainz::Server::ReportScript );

sub GatherData
{
    my $self = shift;

    my $sql = $self->SqlObj;

    $self->GatherDataFromQuery(<<'EOF');
         SELECT url, album.id as release, album.name as name, url.id as urlid
           FROM url, album, l_album_url 
          WHERE link1 = url.id 
            AND link0 = album.id
            AND url ~ 'amazon' 
            AND url !~ 'amazon\.cn'
            AND url !~ '^http://www\.amazon\.(com|ca|de|fr|it|co\.(jp|uk))/gp/product/[0-9A-Z]{10}$'
          ORDER BY url.id 
EOF

}

__PACKAGE__->new->RunReport;

# eof BadAmazonURLs
