#!/home/httpd/musicbrainz/mb_server/cgi-bin/perl -w
# vi: set ts=4 sw=4 :
#____________________________________________________________________________
#
#   MusicBrainz -- the open internet music database
#
#   Copyright (C) 1998 Robert Kaye
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   $Id$
#____________________________________________________________________________

use FindBin;
use lib "$FindBin::Bin/../../cgi-bin";

use strict;
use warnings;

package BadWin32CDTOCs;
use base qw( MusicBrainz::Server::ReportScript );

sub GatherData
{
	my $self = shift;

	my $sql = $self->SqlObj;

	$self->GatherDataFromQuery(<<'EOF');
select	ar_1.id AS artist_id_1, ar_1.name AS artist_name_1,
		al_1.id AS album_id_1, al_1.name AS album_name_1,
		ar_2.id AS artist_id_2, ar_2.name AS artist_name_2,
		al_2.id AS album_id_2, al_2.name AS album_name_2
from	cdtoc cd_1
			inner join album_cdtoc ac_1 on cd_1.id=ac_1.cdtoc
			inner join album al_1 on al_1.id = ac_1.album
			inner join artist ar_1 on ar_1.id = al_1.artist,
		cdtoc cd_2
			inner join album_cdtoc ac_2 on cd_2.id=ac_2.cdtoc
			inner join album al_2 on al_2.id = ac_2.album
			inner join artist ar_2 on ar_2.id = al_2.artist
where	cd_1.trackoffset = cd_2.trackoffset
and		cd_1.id != cd_2.id
and		cd_1.leadoutoffset + 150 = cd_2.leadoutoffset
order by ar_1.sortname, al_1.name
EOF

}

__PACKAGE__->new->RunReport;

# eof BrokenDiscIDs
