#!/usr/bin/env perl

use warnings;
# vi: set ts=4 sw=4 :
#____________________________________________________________________________
#
#   MusicBrainz -- the open internet music database
#
#   Copyright (C) 1998 Robert Kaye
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   $Id$
#____________________________________________________________________________

use FindBin;
use lib "$FindBin::Bin/../../lib";

use strict;
use warnings;

package BadWin32CDTOCs;
use base qw( MusicBrainz::Server::ReportScript );

sub GatherData
{
    my $self = shift;

    my $sql = $self->SqlObj;

    $self->GatherDataFromQuery(<<'EOF');
        SELECT
                ar_1.id AS artist_id_1,
                ar_1.name AS artist_name_1,
                ar_1.sortname AS artist_sortname_1,
                ar_1.resolution AS artist_resolution_1,
                al_1.id AS album_id_1,
                al_1.name AS album_name_1,

                ar_2.id AS artist_id_2,
                ar_2.name AS artist_name_2,
                ar_2.sortname AS artist_sortname_2,
                ar_2.resolution AS artist_resolution_2,
                al_2.id AS album_id_2,
                al_2.name AS album_name_2
        from
                cdtoc cd_1
                INNER JOIN album_cdtoc ac_1 ON cd_1.id=ac_1.cdtoc
                INNER JOIN album al_1 ON al_1.id = ac_1.album
                INNER JOIN artist ar_1 ON ar_1.id = al_1.artist,
                cdtoc cd_2
                INNER JOIN album_cdtoc ac_2 ON cd_2.id=ac_2.cdtoc
                INNER JOIN album al_2 ON al_2.id = ac_2.album
                INNER JOIN artist ar_2 ON ar_2.id = al_2.artist
        WHERE
                cd_1.trackoffset = cd_2.trackoffset
                AND     cd_1.id != cd_2.id
                AND     cd_1.leadoutoffset + 150 = cd_2.leadoutoffset
        ORDER BY
                ar_1.sortname, al_1.name
EOF

}

__PACKAGE__->new->RunReport;

# eof BrokenDiscIDs
