#!/usr/bin/perl -w
# vi: set ts=4 sw=4 :
#____________________________________________________________________________
#
#   MusicBrainz -- the open internet music database
#
#   Copyright (C) 2006 Robert Kaye
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   $Id$
#____________________________________________________________________________

use FindBin;
use lib "$FindBin::Bin/../../lib";

use strict;
use warnings;

package NoLanguage;
use base qw( MusicBrainz::Server::ReportScript );

sub GatherData
{
	my $self = shift;

	my $sql = $self->SqlObj;

	$self->GatherDataFromQuery(<<'EOF');
		SELECT
			al.id AS album_id,
			al.name AS album_name,
			al.modpending AS album_modpending,
			ar.id AS artist_id,
			ar.name AS artist_name,
			ar.sortname AS artist_sortname,
			ar.resolution AS artist_resolution,
			ar.modpending AS artist_modpending
		FROM
			artist ar
		JOIN
			album al
			ON al.artist = ar.id
			WHERE
				al.script NOTNULL
				AND al.language ISNULL
		ORDER BY
			ar.sortname, al.name
EOF

}

__PACKAGE__->new->RunReport;

# eof NoLanguage
