fsync = 'off'
full_page_writes = 'off'
listen_addresses = '0.0.0.0'
log_connections = 'on'
log_disconnections = 'on'
log_min_messages = 'INFO'
log_statement = 'all'
shared_preload_libraries = 'pg_amqp.so'
synchronous_commit = 'off'
