name: Cleanup GHCR images

on:
  schedule:
    # Run daily at midnight UTC
    - cron: "0 0 * * *"

jobs:
  cleanup-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - run: python3 admin/cleanup_ghcr_images.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
